name: auth-service

networks:
  dev:

services:
  db:
    image: postgres:17.0-alpine
    container_name: auth-service-db
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U service -d auth"
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 3
    restart: always
    networks:
      - dev
  app:
    container_name: auth-service-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev
